# Our first notebook

Here we are learning Phyton Variables and some useful methods

## Variables

In [1]:
mycal = 2 + 2
mycal

4

In [2]:
mystr = "let's do it"

In [3]:
mystr

"let's do it"

In [4]:
mydiv = 37 / 3
mydiv

12.333333333333334

In [5]:
my-div = 8 / 9

SyntaxError: can't assign to operator (<ipython-input-5-ad4c3460bd00>, line 1)

## Data types

In [6]:
type(mycal)

int

In [7]:
type(mydiv)

float

In [8]:
type(mystr)

str

In [ ]:
help() # to close help you need to press ctrl+C and then ctrl+Enter

## Libraries

In [9]:
import pandas

In [10]:
% who

mycal	 mydiv	 mystr	 pandas

In [12]:
anz = pandas.read_csv('../data/gapminder_gdp_oceania.csv')

In [13]:
anz

,country,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
0,Australia,10039.59564,10949.64959,12217.22686,14526.12465,16788.62948,18334.19751,19477.00928,21888.88903,23424.76683,26997.93657,30687.75473,34435.36744
1,New Zealand,10556.57566,12247.39532,13175.67800,14463.91893,16046.03728,16233.71770,17632.41040,19007.19129,18363.32494,21050.41377,23189.80135,25185.00911

Every piece of information in python has an index, by default this is 0, 1, 2, etc. as in this cell

In [17]:
anz = pandas.read_csv('../data/gapminder_gdp_oceania.csv', index_col = 'country') # change index to the name of the country

In [15]:
anz

,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
country,,,,,,,,,,,,
Australia,10039.59564,10949.64959,12217.22686,14526.12465,16788.62948,18334.19751,19477.00928,21888.88903,23424.76683,26997.93657,30687.75473,34435.36744
New Zealand,10556.57566,12247.39532,13175.67800,14463.91893,16046.03728,16233.71770,17632.41040,19007.19129,18363.32494,21050.41377,23189.80135,25185.00911

In [18]:
info(anz)

NameError: name 'info' is not defined

In [19]:
.info(anz)

SyntaxError: invalid syntax (<ipython-input-19-fb879de56b32>, line 1)

In [20]:
africa = pandas.read_csv('../data/gapminder_gdp_africa.csv' , index_col = "country")

In [21]:
europe = pandas.read_csv('../data/gapminder_gdp_europe.csv' , index_col = "country")

In [22]:
africa

,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
country,,,,,,,,,,,,
Algeria,2449.008185,3013.976023,2550.816880,3246.991771,4182.663766,4910.416756,5745.160213,5681.358539,5023.216647,4797.295051,5288.040382,6223.367465
Angola,3520.610273,3827.940465,4269.276742,5522.776375,5473.288005,3008.647355,2756.953672,2430.208311,2627.845685,2277.140884,2773.287312,4797.231267
Benin,1062.752200,959.601080,949.499064,1035.831411,1085.796879,1029.161251,1277.897616,1225.856010,1191.207681,1232.975292,1372.877931,1441.284873
Botswana,851.241141,918.232535,983.653976,1214.709294,2263.611114,3214.857818,4551.142150,6205.883850,7954.111645,8647.142313,11003.605080,12569.851770
Burkina Faso,543.255241,617.183465,722.512021,794.826560,854.735976,743.387037,807.198586,912.063142,931.752773,946.294962,1037.645221,1217.032994
Burundi,339.296459,379.564628,355.203227,412.977514,464.099504,556.103265,559.603231,621.818819,631.699878,463.115148,446.403513,430.070692
Cameroon,1172.667655,1313.048099,1399.607441,1508.453148,1684.146528,1783.432873,2367.983282,2602.664206,1793.163278,1694.337469,1934.011449,2042.095240
Central African Republic,1071.310713,1190.844328,1193.068753,1136.056615,1070.013275,1109.374338,956.752991,844.876350,747.905525,740.506332,738.690607,706.016537
Chad,1178.665927,1308.495577,1389.817618,1196.810565,1104.103987,1133.984950,797.908101,952.386129,1058.064300,1004.961353,1156.181860,1704.063724
Comoros,1102.990936,1211.148548,1406.648278,1876.029643,1937.577675,1172.603047,1267.100083,1315.980812,1246.907370,1173.618235,1075.811558,986.147879
Congo Dem. Rep.,780.542326,905.860230,896.314634,861.593242,904.896069,795.757282,673.747818,672.774812,457.719181,312.188423,241.165877,277.551859
Congo Rep.,2125.621418,2315.056572,2464.783157,2677.939642,3213.152683,3259.178978,4879.507522,4201.194937,4016.239529,3484.164376,3484.061970,3632.557798
Cote d'Ivoire,1388.594732,1500.895925,1728.869428,2052.050473,2378.201111,2517.736547,2602.710169,2156.956069,1648.073791,1786.265407,1648.800823,1544.750112
Djibouti,2669.529475,2864.969076,3020.989263,3020.050513,3694.212352,3081.761022,2879.468067,2880.102568,2377.156192,1895.016984,1908.260867,2082.481567
Egypt,1418.822445,1458.915272,1693.335853,1814.880728,2024.008147,2785.493582,3503.729636,3885.460710,3794.755195,4173.181797,4754.604414,5581.180998
Equatorial Guinea,375.643123,426.096408,582.841971,915.596003,672.412257,958.566812,927.825343,966.896815,1132.055034,2814.480755,7703.495900,12154.089750
Eritrea,328.940557,344.161886,380.995843,468.794970,514.324208,505.753808,524.875849,521.134133,582.858510,913.470790,765.350001,641.369524
Ethiopia,362.146280,378.904163,419.456416,516.118644,566.243944,556.808383,577.860747,573.741314,421.353465,515.889401,530.053532,690.805576
Gabon,4293.476475,4976.198099,6631.459222,8358.761987,11401.948410,21745.573280,15113.361940,11864.408440,13522.157520,14722.841880,12521.713920,13206.484520
Gambia,485.230659,520.926711,599.650276,734.782912,756.086836,884.755251,835.809611,611.658861,665.624413,653.730170,660.585600,752.749726
Ghana,911.298937,1043.561537,1190.041118,1125.697160,1178.223708,993.223957,876.032569,847.006113,925.060154,1005.245812,1111.984578,1327.608910
Guinea,510.196492,576.267025,686.373674,708.759541,741.666231,874.685864,857.250358,805.572472,794.348438,869.449767,945.583584,942.654211
Guinea-Bissau,299.850319,431.790457,522.034373,715.580640,820.224588,764.725963,838.123967,736.415392,745.539871,796.664468,575.704718,579.231743
Kenya,853.540919,944.438315,896.966373,1056.736457,1222.359968,1267.613204,1348.225791,1361.936856,1341.921721,1360.485021,1287.514732,1463.249282
Lesotho,298.846212,335.997115,411.800627,498.639026,496.581592,745.369541,797.263107,773.993214,977.486272,1186.147994,1275.184575,1569.331442
Liberia,575.572996,620.969990,634.195163,713.603648,803.005454,640.322438,572.199569,506.113857,636.622919,609.173951,531.482368,414.507341
Libya,2387.548060,3448.284395,6757.030816,18772.751690,21011.497210,21951.211760,17364.275380,11770.589800,9640.138501,9467.446056,9534.677467,12057.499280
Madagascar,1443.011715,1589.202750,1643.387110,1634.047282,1748.562982,1544.228586,1302.878658,1155.441948,1040.676190,986.295896,894.637082,1044.770126
Malawi,369.165080,416.369806,427.901086,495.514781,584.621971,663.223677,632.803921,635.517363,563.200014,692.275810,665.423119,759.349910
Mali,452.336981,490.382187,496.174343,545.009887,581.368876,686.395269,618.014064,684.171558,739.014375,790.257985,951.409752,1042.581557
Mauritania,743.115910,846.120261,1055.896036,1421.145193,1586.851781,1497.492223,1481.150189,1421.603576,1361.369784,1483.136136,1579.019543,1803.151496
Mauritius,1967.955707,2034.037981,2529.067487,2475.387562,2575.484158,3710.982963,3688.037739,4783.586903,6058.253846,7425.705295,9021.815894,10956.991120
Morocco,1688.203570,1642.002314,1566.353493,1711.044770,1930.194975,2370.619976,2702.620356,2755.046991,2948.047252,2982.101858,3258.495584,3820.175230
Mozambique,468.526038,495.586833,556.686354,566.669154,724.917804,502.319733,462.211415,389.876185,410.896824,472.346077,633.617947,823.685621
Namibia,2423.780443,2621.448058,3173.215595,3793.694753,3746.080948,3876.485958,4191.100511,3693.731337,3804.537999,3899.524260,4072.324751,4811.060429
Niger,761.879376,835.523403,997.766113,1054.384891,954.209236,808.897073,909.722135,668.300023,581.182725,580.305209,601.074501,619.676892
Nigeria,1077.281856,1100.592563,1150.927478,1014.514104,1698.388838,1981.951806,1576.973750,1385.029563,1619.848217,1624.941275,1615.286395,2013.977305
Reunion,2718.885295,2769.451844,3173.723340,4021.175739,5047.658563,4319.804067,5267.219353,5303.377488,6101.255823,6071.941411,6316.165200,7670.122558
Rwanda,493.323875,540.289398,597.473073,510.963714,590.580664,670.080601,881.570647,847.991217,737.068595,589.944505,785.653765,863.088464
Sao Tome and Principe,879.583586,860.736903,1071.551119,1384.840593,1532.985254,1737.561657,1890.218117,1516.525457,1428.777814,1339.076036,1353.092390,1598.435089
Senegal,1450.356983,1567.653006,1654.988723,1612.404632,1597.712056,1561.769116,1518.479984,1441.720720,1367.899369,1392.368347,1519.635262,1712.472136
Sierra Leone,879.787736,1004.484437,1116.639877,1206.043465,1353.759762,1348.285159,1465.010784,1294.447788,1068.696278,574.648158,699.489713,862.540756
Somalia,1135.749842,1258.147413,1369.488336,1284.733180,1254.576127,1450.992513,1176.807031,1093.244963,926.960296,930.596428,882.081822,926.141068
South Africa,4725.295531,5487.104219,5768.729717,7114.477971,7765.962636,8028.651439,8568.266228,7825.823398,7225.069258,7479.188244,7710.946444,9269.657808
Sudan,1615.991129,1770.337074,1959.593767,1687.997641,1659.652775,2202.988423,1895.544073,1507.819159,1492.197043,1632.210764,1993.398314,2602.394995
Swaziland,1148.376626,1244.708364,1856.182125,2613.101665,3364.836625,3781.410618,3895.384018,3984.839812,3553.022400,3876.768460,4128.116943,4513.480643
Tanzania,716.650072,698.535607,722.003807,848.218657,915.985059,962.492293,874.242607,831.822079,825.682454,789.186223,899.074211,1107.482182
Togo,859.808657,925.908320,1067.534810,1477.596760,1649.660188,1532.776998,1344.577953,1202.201361,1034.298904,982.286924,886.220577,882.969944
Tunisia,1468.475631,1395.232468,1660.303210,1932.360167,2753.285994,3120.876811,3560.233174,3810.419296,4332.720164,4876.798614,5722.895655,7092.923025
Uganda,734.753484,774.371069,767.271740,908.918522,950.735869,843.733137,682.266227,617.724406,644.170797,816.559081,927.721002,1056.380121
Zambia,1147.388831,1311.956766,1452.725766,1777.077318,1773.498265,1588.688299,1408.678565,1213.315116,1210.884633,1071.353818,1071.613938,1271.211593
Zimbabwe,406.884115,518.764268,527.272182,569.795071,799.362176,685.587682,788.855041,706.157306,693.420786,792.449960,672.038623,469.709298

In [23]:
europe

,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
country,,,,,,,,,,,,
Albania,1601.056136,1942.284244,2312.888958,2760.196931,3313.422188,3533.003910,3630.880722,3738.932735,2497.437901,3193.054604,4604.211737,5937.029526
Austria,6137.076492,8842.598030,10750.721110,12834.602400,16661.625600,19749.422300,21597.083620,23687.826070,27042.018680,29095.920660,32417.607690,36126.492700
Belgium,8343.105127,9714.960623,10991.206760,13149.041190,16672.143560,19117.974480,20979.845890,22525.563080,25575.570690,27561.196630,30485.883750,33692.605080
Bosnia and Herzegovina,973.533195,1353.989176,1709.683679,2172.352423,2860.169750,3528.481305,4126.613157,4314.114757,2546.781445,4766.355904,6018.975239,7446.298803
Bulgaria,2444.286648,3008.670727,4254.337839,5577.002800,6597.494398,7612.240438,8224.191647,8239.854824,6302.623438,5970.388760,7696.777725,10680.792820
Croatia,3119.236520,4338.231617,5477.890018,6960.297861,9164.090127,11305.385170,13221.821840,13822.583940,8447.794873,9875.604515,11628.388950,14619.222720
Czech Republic,6876.140250,8256.343918,10136.867130,11399.444890,13108.453600,14800.160620,15377.228550,16310.443400,14297.021220,16048.514240,17596.210220,22833.308510
Denmark,9692.385245,11099.659350,13583.313510,15937.211230,18866.207210,20422.901500,21688.040480,25116.175810,26406.739850,29804.345670,32166.500060,35278.418740
Finland,6424.519071,7545.415386,9371.842561,10921.636260,14358.875900,15605.422830,18533.157610,21141.012230,20647.164990,23723.950200,28204.590570,33207.084400
France,7029.809327,8662.834898,10560.485530,12999.917660,16107.191710,18292.635140,20293.897460,22066.442140,24703.796150,25889.784870,28926.032340,30470.016700
Germany,7144.114393,10187.826650,12902.462910,14745.625610,18016.180270,20512.921230,22031.532740,24639.185660,26505.303170,27788.884160,30035.801980,32170.374420
Greece,3530.690067,4916.299889,6017.190733,8513.097016,12724.829570,14195.524280,15268.420890,16120.528390,17541.496340,18747.698140,22514.254800,27538.411880
Hungary,5263.673816,6040.180011,7550.359877,9326.644670,10168.656110,11674.837370,12545.990660,12986.479980,10535.628550,11712.776800,14843.935560,18008.944440
Iceland,7267.688428,9244.001412,10350.159060,13319.895680,15798.063620,19654.962470,23269.607500,26923.206280,25144.392010,28061.099660,31163.201960,36180.789190
Ireland,5210.280328,5599.077872,6631.597314,7655.568963,9530.772896,11150.981130,12618.321410,13872.866520,17558.815550,24521.947130,34077.049390,40675.996350
Italy,4931.404155,6248.656232,8243.582340,10022.401310,12269.273780,14255.984750,16537.483500,19207.234820,22013.644860,24675.024460,27968.098170,28569.719700
Montenegro,2647.585601,3682.259903,4649.593785,5907.850937,7778.414017,9595.929905,11222.587620,11732.510170,7003.339037,6465.613349,6557.194282,9253.896111
Netherlands,8941.571858,11276.193440,12790.849560,15363.251360,18794.745670,21209.059200,21399.460460,23651.323610,26790.949610,30246.130630,33724.757780,36797.933320
Norway,10095.421720,11653.973040,13450.401510,16361.876470,18965.055510,23311.349390,26298.635310,31540.974800,33965.661150,41283.164330,44683.975250,49357.190170
Poland,4029.329699,4734.253019,5338.752143,6557.152776,8006.506993,9508.141454,8451.531004,9082.351172,7738.881247,10159.583680,12002.239080,15389.924680
Portugal,3068.319867,3774.571743,4727.954889,6361.517993,9022.247417,10172.485720,11753.842910,13039.308760,16207.266630,17641.031560,19970.907870,20509.647770
Romania,3144.613186,3943.370225,4734.997586,6470.866545,8011.414402,9356.397240,9605.314053,9696.273295,6598.409903,7346.547557,7885.360081,10808.475610
Serbia,3581.459448,4981.090891,6289.629157,7991.707066,10522.067490,12980.669560,15181.092700,15870.878510,9325.068238,7914.320304,7236.075251,9786.534714
Slovak Republic,5074.659104,6093.262980,7481.107598,8412.902397,9674.167626,10922.664040,11348.545850,12037.267580,9498.467723,12126.230650,13638.778370,18678.314350
Slovenia,4215.041741,5862.276629,7402.303395,9405.489397,12383.486200,15277.030170,17866.721750,18678.534920,14214.716810,17161.107350,20660.019360,25768.257590
Spain,3834.034742,4564.802410,5693.843879,7993.512294,10638.751310,13236.921170,13926.169970,15764.983130,18603.064520,20445.298960,24835.471660,28821.063700
Sweden,8527.844662,9911.878226,12329.441920,15258.296970,17832.024640,18855.725210,20667.381250,23586.929270,23880.016830,25266.594990,29341.630930,33859.748350
Switzerland,14734.232750,17909.489730,20431.092700,22966.144320,27195.113040,26982.290520,28397.715120,30281.704590,31871.530300,32135.323010,34480.957710,37506.419070
Turkey,1969.100980,2218.754257,2322.869908,2826.356387,3450.696380,4269.122326,4241.356344,5089.043686,5678.348271,6601.429915,6508.085718,8458.276384
United Kingdom,9979.508487,11283.177950,12477.177070,14142.850890,15895.116410,17428.748460,18232.424520,21664.787670,22705.092540,26074.531360,29478.999190,33203.261280

In [24]:
anz.columns # column names

Index(['gdpPercap_1952', 'gdpPercap_1957', 'gdpPercap_1962', 'gdpPercap_1967',
       'gdpPercap_1972', 'gdpPercap_1977', 'gdpPercap_1982', 'gdpPercap_1987',
       'gdpPercap_1992', 'gdpPercap_1997', 'gdpPercap_2002', 'gdpPercap_2007'],
      dtype='object')

In [25]:
anz.index # row names

Index(['Australia', 'New Zealand'], dtype='object', name='country')

In [26]:
anz.axes # x-axis is rows and y-axis is columns

[Index(['Australia', 'New Zealand'], dtype='object', name='country'),
 Index(['gdpPercap_1952', 'gdpPercap_1957', 'gdpPercap_1962', 'gdpPercap_1967',
        'gdpPercap_1972', 'gdpPercap_1977', 'gdpPercap_1982', 'gdpPercap_1987',
        'gdpPercap_1992', 'gdpPercap_1997', 'gdpPercap_2002', 'gdpPercap_2007'],
       dtype='object')]

In [27]:
anz.dtypes # float64 is the default float in pandas

gdpPercap_1952    float64
gdpPercap_1957    float64
gdpPercap_1962    float64
gdpPercap_1967    float64
gdpPercap_1972    float64
gdpPercap_1977    float64
gdpPercap_1982    float64
gdpPercap_1987    float64
gdpPercap_1992    float64
gdpPercap_1997    float64
gdpPercap_2002    float64
gdpPercap_2007    float64
dtype: object

In [28]:
anz.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, Australia to New Zealand
Data columns (total 12 columns):
gdpPercap_1952    2 non-null float64
gdpPercap_1957    2 non-null float64
gdpPercap_1962    2 non-null float64
gdpPercap_1967    2 non-null float64
gdpPercap_1972    2 non-null float64
gdpPercap_1977    2 non-null float64
gdpPercap_1982    2 non-null float64
gdpPercap_1987    2 non-null float64
gdpPercap_1992    2 non-null float64
gdpPercap_1997    2 non-null float64
gdpPercap_2002    2 non-null float64
gdpPercap_2007    2 non-null float64
dtypes: float64(12)
memory usage: 208.0+ bytes

In [29]:
anz.shape # number of rows and columns (not counting the index, in this case the country because we made that the index)

(2, 12)

In [30]:
anz.size # total number of values

24

In [31]:
anz.values # array representation of all values

array([[10039.59564, 10949.64959, 12217.22686, 14526.12465, 16788.62948,
        18334.19751, 19477.00928, 21888.88903, 23424.76683, 26997.93657,
        30687.75473, 34435.36744],
       [10556.57566, 12247.39532, 13175.678  , 14463.91893, 16046.03728,
        16233.7177 , 17632.4104 , 19007.19129, 18363.32494, 21050.41377,
        23189.80135, 25185.00911]])

In [32]:
anz.T # transpose: reverse rows and columns

country           Australia  New Zealand
gdpPercap_1952  10039.59564  10556.57566
gdpPercap_1957  10949.64959  12247.39532
gdpPercap_1962  12217.22686  13175.67800
gdpPercap_1967  14526.12465  14463.91893
gdpPercap_1972  16788.62948  16046.03728
gdpPercap_1977  18334.19751  16233.71770
gdpPercap_1982  19477.00928  17632.41040
gdpPercap_1987  21888.88903  19007.19129
gdpPercap_1992  23424.76683  18363.32494
gdpPercap_1997  26997.93657  21050.41377
gdpPercap_2002  30687.75473  23189.80135
gdpPercap_2007  34435.36744  25185.00911

In [33]:
anz.ndim # number of dimensions (usually x + y dimension)

2

In [34]:
del mycal
% who

africa	 anz	 europe	 mydiv	 mystr	 pandas

In [35]:
del mydiv
del mystr
% who

africa	 anz	 europe	 pandas

In [36]:
africa.info() # summary info

<class 'pandas.core.frame.DataFrame'>
Index: 52 entries, Algeria to Zimbabwe
Data columns (total 12 columns):
gdpPercap_1952    52 non-null float64
gdpPercap_1957    52 non-null float64
gdpPercap_1962    52 non-null float64
gdpPercap_1967    52 non-null float64
gdpPercap_1972    52 non-null float64
gdpPercap_1977    52 non-null float64
gdpPercap_1982    52 non-null float64
gdpPercap_1987    52 non-null float64
gdpPercap_1992    52 non-null float64
gdpPercap_1997    52 non-null float64
gdpPercap_2002    52 non-null float64
gdpPercap_2007    52 non-null float64
dtypes: float64(12)
memory usage: 5.3+ KB

In [37]:
africa.describe() # summary of statistics per numeric column

,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
count,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000
mean,1252.572466,1385.236062,1598.078825,2050.363801,2339.615674,2585.938508,2481.592960,2282.668991,2281.810333,2378.759555,2599.385159,3089.032605
std,982.952116,1134.508918,1461.839189,2847.717603,3286.853884,4142.398707,3242.632753,2566.531947,2644.075602,2820.728117,2972.651308,3618.163491
min,298.846212,335.997115,355.203227,412.977514,464.099504,502.319733,462.211415,389.876185,410.896824,312.188423,241.165877,277.551859
25%,534.990554,606.954355,673.329046,779.815648,815.919804,805.612125,828.656854,764.598759,743.908497,791.901966,780.577824,862.951537
50%,987.025569,1024.022987,1133.783677,1210.376379,1443.372508,1399.638836,1323.728306,1219.585563,1161.631357,1179.883114,1215.683217,1452.267078
75%,1454.886645,1573.040442,1702.219247,1890.112274,2292.258613,2841.282025,2787.582271,2786.310885,2707.896077,2856.386031,3314.887180,3993.501583
max,4725.295531,5487.104219,6757.030816,18772.751690,21011.497210,21951.211760,17364.275380,11864.408440,13522.157520,14722.841880,12521.713920,13206.484520

In [41]:
africa.gdpPercap_1952

country
Algeria                     2449.008185
Angola                      3520.610273
Benin                       1062.752200
Botswana                     851.241141
Burkina Faso                 543.255241
Burundi                      339.296459
Cameroon                    1172.667655
Central African Republic    1071.310713
Chad                        1178.665927
Comoros                     1102.990936
Congo Dem. Rep.              780.542326
Congo Rep.                  2125.621418
Cote d'Ivoire               1388.594732
Djibouti                    2669.529475
Egypt                       1418.822445
Equatorial Guinea            375.643123
Eritrea                      328.940557
Ethiopia                     362.146280
Gabon                       4293.476475
Gambia                       485.230659
Ghana                        911.298937
Guinea                       510.196492
Guinea-Bissau                299.850319
Kenya                        853.540919
Lesotho                      298.846212
Liberia                      575.572996
Libya                       2387.548060
Madagascar                  1443.011715
Malawi                       369.165080
Mali                         452.336981
Mauritania                   743.115910
Mauritius                   1967.955707
Morocco                     1688.203570
Mozambique                   468.526038
Namibia                     2423.780443
Niger                        761.879376
Nigeria                     1077.281856
Reunion                     2718.885295
Rwanda                       493.323875
Sao Tome and Principe        879.583586
Senegal                     1450.356983
Sierra Leone                 879.787736
Somalia                     1135.749842
South Africa                4725.295531
Sudan                       1615.991129
Swaziland                   1148.376626
Tanzania                     716.650072
Togo                         859.808657
Tunisia                     1468.475631
Uganda                       734.753484
Zambia                      1147.388831
Zimbabwe                     406.884115
Name: gdpPercap_1952, dtype: float64

In [42]:
africa.gdpPercap_1952.describe() # summary of statistics for a specific column

count      52.000000
mean     1252.572466
std       982.952116
min       298.846212
25%       534.990554
50%       987.025569
75%      1454.886645
max      4725.295531
Name: gdpPercap_1952, dtype: float64

In [38]:
africa.head() # first n rows (5 by default)

,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
country,,,,,,,,,,,,
Algeria,2449.008185,3013.976023,2550.816880,3246.991771,4182.663766,4910.416756,5745.160213,5681.358539,5023.216647,4797.295051,5288.040382,6223.367465
Angola,3520.610273,3827.940465,4269.276742,5522.776375,5473.288005,3008.647355,2756.953672,2430.208311,2627.845685,2277.140884,2773.287312,4797.231267
Benin,1062.752200,959.601080,949.499064,1035.831411,1085.796879,1029.161251,1277.897616,1225.856010,1191.207681,1232.975292,1372.877931,1441.284873
Botswana,851.241141,918.232535,983.653976,1214.709294,2263.611114,3214.857818,4551.142150,6205.883850,7954.111645,8647.142313,11003.605080,12569.851770
Burkina Faso,543.255241,617.183465,722.512021,794.826560,854.735976,743.387037,807.198586,912.063142,931.752773,946.294962,1037.645221,1217.032994

In [39]:
africa.tail() # last n rows (5 by default)

,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
country,,,,,,,,,,,,
Togo,859.808657,925.908320,1067.534810,1477.596760,1649.660188,1532.776998,1344.577953,1202.201361,1034.298904,982.286924,886.220577,882.969944
Tunisia,1468.475631,1395.232468,1660.303210,1932.360167,2753.285994,3120.876811,3560.233174,3810.419296,4332.720164,4876.798614,5722.895655,7092.923025
Uganda,734.753484,774.371069,767.271740,908.918522,950.735869,843.733137,682.266227,617.724406,644.170797,816.559081,927.721002,1056.380121
Zambia,1147.388831,1311.956766,1452.725766,1777.077318,1773.498265,1588.688299,1408.678565,1213.315116,1210.884633,1071.353818,1071.613938,1271.211593
Zimbabwe,406.884115,518.764268,527.272182,569.795071,799.362176,685.587682,788.855041,706.157306,693.420786,792.449960,672.038623,469.709298

In [40]:
africa.head(n=3) # first 3 rows

,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
country,,,,,,,,,,,,
Algeria,2449.008185,3013.976023,2550.816880,3246.991771,4182.663766,4910.416756,5745.160213,5681.358539,5023.216647,4797.295051,5288.040382,6223.367465
Angola,3520.610273,3827.940465,4269.276742,5522.776375,5473.288005,3008.647355,2756.953672,2430.208311,2627.845685,2277.140884,2773.287312,4797.231267
Benin,1062.752200,959.601080,949.499064,1035.831411,1085.796879,1029.161251,1277.897616,1225.856010,1191.207681,1232.975292,1372.877931,1441.284873

In [43]:
americas = pandas.read_csv('../data/gapminder_gdp_americas.csv' , index_col = "country")

In [44]:
americas

,continent,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
country,,,,,,,,,,,,,
Argentina,Americas,5911.315053,6856.856212,7133.166023,8052.953021,9443.038526,10079.026740,8997.897412,9139.671389,9308.418710,10967.281950,8797.640716,12779.379640
Bolivia,Americas,2677.326347,2127.686326,2180.972546,2586.886053,2980.331339,3548.097832,3156.510452,2753.691490,2961.699694,3326.143191,3413.262690,3822.137084
Brazil,Americas,2108.944355,2487.365989,3336.585802,3429.864357,4985.711467,6660.118654,7030.835878,7807.095818,6950.283021,7957.980824,8131.212843,9065.800825
Canada,Americas,11367.161120,12489.950060,13462.485550,16076.588030,18970.570860,22090.883060,22898.792140,26626.515030,26342.884260,28954.925890,33328.965070,36319.235010
Chile,Americas,3939.978789,4315.622723,4519.094331,5106.654313,5494.024437,4756.763836,5095.665738,5547.063754,7596.125964,10118.053180,10778.783850,13171.638850
Colombia,Americas,2144.115096,2323.805581,2492.351109,2678.729839,3264.660041,3815.807870,4397.575659,4903.219100,5444.648617,6117.361746,5755.259962,7006.580419
Costa Rica,Americas,2627.009471,2990.010802,3460.937025,4161.727834,5118.146939,5926.876967,5262.734751,5629.915318,6160.416317,6677.045314,7723.447195,9645.061420
Cuba,Americas,5586.538780,6092.174359,5180.755910,5690.268015,5305.445256,6380.494966,7316.918107,7532.924763,5592.843963,5431.990415,6340.646683,8948.102923
Dominican Republic,Americas,1397.717137,1544.402995,1662.137359,1653.723003,2189.874499,2681.988900,2861.092386,2899.842175,3044.214214,3614.101285,4563.808154,6025.374752
Ecuador,Americas,3522.110717,3780.546651,4086.114078,4579.074215,5280.994710,6679.623260,7213.791267,6481.776993,7103.702595,7429.455877,5773.044512,6873.262326
El Salvador,Americas,3048.302900,3421.523218,3776.803627,4358.595393,4520.246008,5138.922374,4098.344175,4140.442097,4444.231700,5154.825496,5351.568666,5728.353514
Guatemala,Americas,2428.237769,2617.155967,2750.364446,3242.531147,4031.408271,4879.992748,4820.494790,4246.485974,4439.450840,4684.313807,4858.347495,5186.050003
Haiti,Americas,1840.366939,1726.887882,1796.589032,1452.057666,1654.456946,1874.298931,2011.159549,1823.015995,1456.309517,1341.726931,1270.364932,1201.637154
Honduras,Americas,2194.926204,2220.487682,2291.156835,2538.269358,2529.842345,3203.208066,3121.760794,3023.096699,3081.694603,3160.454906,3099.728660,3548.330846
Jamaica,Americas,2898.530881,4756.525781,5246.107524,6124.703451,7433.889293,6650.195573,6068.051350,6351.237495,7404.923685,7121.924704,6994.774861,7320.880262
Mexico,Americas,3478.125529,4131.546641,4581.609385,5754.733883,6809.406690,7674.929108,9611.147541,8688.156003,9472.384295,9767.297530,10742.440530,11977.574960
Nicaragua,Americas,3112.363948,3457.415947,3634.364406,4643.393534,4688.593267,5486.371089,3470.338156,2955.984375,2170.151724,2253.023004,2474.548819,2749.320965
Panama,Americas,2480.380334,2961.800905,3536.540301,4421.009084,5364.249663,5351.912144,7009.601598,7034.779161,6618.743050,7113.692252,7356.031934,9809.185636
Paraguay,Americas,1952.308701,2046.154706,2148.027146,2299.376311,2523.337977,3248.373311,4258.503604,3998.875695,4196.411078,4247.400261,3783.674243,4172.838464
Peru,Americas,3758.523437,4245.256698,4957.037982,5788.093330,5937.827283,6281.290855,6434.501797,6360.943444,4446.380924,5838.347657,5909.020073,7408.905561
Puerto Rico,Americas,3081.959785,3907.156189,5108.344630,6929.277714,9123.041742,9770.524921,10330.989150,12281.341910,14641.587110,16999.433300,18855.606180,19328.709010
Trinidad and Tobago,Americas,3023.271928,4100.393400,4997.523971,5621.368472,6619.551419,7899.554209,9119.528607,7388.597823,7370.990932,8792.573126,11460.600230,18008.509240
United States,Americas,13990.482080,14847.127120,16173.145860,19530.365570,21806.035940,24072.632130,25009.559140,29884.350410,32003.932240,35767.433030,39097.099550,42951.653090
Uruguay,Americas,5716.766744,6150.772969,5603.357717,5444.619620,5703.408898,6504.339663,6920.223051,7452.398969,8137.004775,9230.240708,7727.002004,10611.462990
Venezuela,Americas,7689.799761,9802.466526,8422.974165,9541.474188,10505.259660,13143.950950,11152.410110,9883.584648,10733.926310,10165.495180,8605.047831,11415.805690

In [45]:
americas.head(n=3) # you can also type americas.head(3) because n is the first option of head

,continent,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
country,,,,,,,,,,,,,
Argentina,Americas,5911.315053,6856.856212,7133.166023,8052.953021,9443.038526,10079.026740,8997.897412,9139.671389,9308.418710,10967.281950,8797.640716,12779.379640
Bolivia,Americas,2677.326347,2127.686326,2180.972546,2586.886053,2980.331339,3548.097832,3156.510452,2753.691490,2961.699694,3326.143191,3413.262690,3822.137084
Brazil,Americas,2108.944355,2487.365989,3336.585802,3429.864357,4985.711467,6660.118654,7030.835878,7807.095818,6950.283021,7957.980824,8131.212843,9065.800825

In [46]:
americas.tail(n=3) # you can also type americas.tail(3) because n is the first option of tail

,continent,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
country,,,,,,,,,,,,,
United States,Americas,13990.482080,14847.127120,16173.145860,19530.365570,21806.035940,24072.632130,25009.559140,29884.350410,32003.932240,35767.433030,39097.099550,42951.65309
Uruguay,Americas,5716.766744,6150.772969,5603.357717,5444.619620,5703.408898,6504.339663,6920.223051,7452.398969,8137.004775,9230.240708,7727.002004,10611.46299
Venezuela,Americas,7689.799761,9802.466526,8422.974165,9541.474188,10505.259660,13143.950950,11152.410110,9883.584648,10733.926310,10165.495180,8605.047831,11415.80569

In [47]:
americas.describe()

,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
count,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000
mean,4079.062552,4616.043733,4901.541870,5668.253496,6491.334139,7352.007126,7506.737088,7793.400261,8044.934406,8889.300863,9287.677107,11003.031625
std,3001.727522,3312.381083,3421.740569,4160.885560,4754.404329,5355.602518,5530.490471,6665.039509,7047.089191,7874.225145,8895.817785,9713.209302
min,1397.717137,1544.402995,1662.137359,1452.057666,1654.456946,1874.298931,2011.159549,1823.015995,1456.309517,1341.726931,1270.364932,1201.637154
25%,2428.237769,2487.365989,2750.364446,3242.531147,4031.408271,4756.763836,4258.503604,4140.442097,4439.450840,4684.313807,4858.347495,5728.353514
50%,3048.302900,3780.546651,4086.114078,4643.393534,5305.445256,6281.290855,6434.501797,6360.943444,6618.743050,7113.692252,6994.774861,8948.102923
75%,3939.978789,4756.525781,5180.755910,5788.093330,6809.406690,7674.929108,8997.897412,7807.095818,8137.004775,9767.297530,8797.640716,11977.574960
max,13990.482080,14847.127120,16173.145860,19530.365570,21806.035940,24072.632130,25009.559140,29884.350410,32003.932240,35767.433030,39097.099550,42951.653090

In [48]:
americas.T

country,Argentina,Bolivia,Brazil,Canada,Chile,Colombia,Costa Rica,Cuba,Dominican Republic,Ecuador,...,Mexico,Nicaragua,Panama,Paraguay,Peru,Puerto Rico,Trinidad and Tobago,United States,Uruguay,Venezuela
continent,Americas,Americas,Americas,Americas,Americas,Americas,Americas,Americas,Americas,Americas,...,Americas,Americas,Americas,Americas,Americas,Americas,Americas,Americas,Americas,Americas
gdpPercap_1952,5911.32,2677.33,2108.94,11367.2,3939.98,2144.12,2627.01,5586.54,1397.72,3522.11,...,3478.13,3112.36,2480.38,1952.31,3758.52,3081.96,3023.27,13990.5,5716.77,7689.8
gdpPercap_1957,6856.86,2127.69,2487.37,12490,4315.62,2323.81,2990.01,6092.17,1544.4,3780.55,...,4131.55,3457.42,2961.8,2046.15,4245.26,3907.16,4100.39,14847.1,6150.77,9802.47
gdpPercap_1962,7133.17,2180.97,3336.59,13462.5,4519.09,2492.35,3460.94,5180.76,1662.14,4086.11,...,4581.61,3634.36,3536.54,2148.03,4957.04,5108.34,4997.52,16173.1,5603.36,8422.97
gdpPercap_1967,8052.95,2586.89,3429.86,16076.6,5106.65,2678.73,4161.73,5690.27,1653.72,4579.07,...,5754.73,4643.39,4421.01,2299.38,5788.09,6929.28,5621.37,19530.4,5444.62,9541.47
gdpPercap_1972,9443.04,2980.33,4985.71,18970.6,5494.02,3264.66,5118.15,5305.45,2189.87,5280.99,...,6809.41,4688.59,5364.25,2523.34,5937.83,9123.04,6619.55,21806,5703.41,10505.3
gdpPercap_1977,10079,3548.1,6660.12,22090.9,4756.76,3815.81,5926.88,6380.49,2681.99,6679.62,...,7674.93,5486.37,5351.91,3248.37,6281.29,9770.52,7899.55,24072.6,6504.34,13144
gdpPercap_1982,8997.9,3156.51,7030.84,22898.8,5095.67,4397.58,5262.73,7316.92,2861.09,7213.79,...,9611.15,3470.34,7009.6,4258.5,6434.5,10331,9119.53,25009.6,6920.22,11152.4
gdpPercap_1987,9139.67,2753.69,7807.1,26626.5,5547.06,4903.22,5629.92,7532.92,2899.84,6481.78,...,8688.16,2955.98,7034.78,3998.88,6360.94,12281.3,7388.6,29884.4,7452.4,9883.58
gdpPercap_1992,9308.42,2961.7,6950.28,26342.9,7596.13,5444.65,6160.42,5592.84,3044.21,7103.7,...,9472.38,2170.15,6618.74,4196.41,4446.38,14641.6,7370.99,32003.9,8137,10733.9
gdpPercap_1997,10967.3,3326.14,7957.98,28954.9,10118.1,6117.36,6677.05,5431.99,3614.1,7429.46,...,9767.3,2253.02,7113.69,4247.4,5838.35,16999.4,8792.57,35767.4,9230.24,10165.5
gdpPercap_2002,8797.64,3413.26,8131.21,33329,10778.8,5755.26,7723.45,6340.65,4563.81,5773.04,...,10742.4,2474.55,7356.03,3783.67,5909.02,18855.6,11460.6,39097.1,7727,8605.05
gdpPercap_2007,12779.4,3822.14,9065.8,36319.2,13171.6,7006.58,9645.06,8948.1,6025.37,6873.26,...,11977.6,2749.32,9809.19,4172.84,7408.91,19328.7,18008.5,42951.7,10611.5,11415.8

In [53]:
processed = americas.T.tail(n=3).T # you could also make an intermediate variable instead of doing everything in one step

In [55]:
processed.columns

Index(['gdpPercap_1997', 'gdpPercap_2002', 'gdpPercap_2007'], dtype='object')

In [57]:
processed.columns.format() # you could save this as another variable and use it for further analyses

['gdpPercap_1997', 'gdpPercap_2002', 'gdpPercap_2007']

In [58]:
europe.iloc # subset a part of the dataframe using the row index
europe.loc # subset a part of the dataframe using the row name
favoritecountry = europe.loc["Belgium"]

In [59]:
favoritecountry

gdpPercap_1952     8343.105127
gdpPercap_1957     9714.960623
gdpPercap_1962    10991.206760
gdpPercap_1967    13149.041190
gdpPercap_1972    16672.143560
gdpPercap_1977    19117.974480
gdpPercap_1982    20979.845890
gdpPercap_1987    22525.563080
gdpPercap_1992    25575.570690
gdpPercap_1997    27561.196630
gdpPercap_2002    30485.883750
gdpPercap_2007    33692.605080
Name: Belgium, dtype: float64

In [60]:
europe

,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
country,,,,,,,,,,,,
Albania,1601.056136,1942.284244,2312.888958,2760.196931,3313.422188,3533.003910,3630.880722,3738.932735,2497.437901,3193.054604,4604.211737,5937.029526
Austria,6137.076492,8842.598030,10750.721110,12834.602400,16661.625600,19749.422300,21597.083620,23687.826070,27042.018680,29095.920660,32417.607690,36126.492700
Belgium,8343.105127,9714.960623,10991.206760,13149.041190,16672.143560,19117.974480,20979.845890,22525.563080,25575.570690,27561.196630,30485.883750,33692.605080
Bosnia and Herzegovina,973.533195,1353.989176,1709.683679,2172.352423,2860.169750,3528.481305,4126.613157,4314.114757,2546.781445,4766.355904,6018.975239,7446.298803
Bulgaria,2444.286648,3008.670727,4254.337839,5577.002800,6597.494398,7612.240438,8224.191647,8239.854824,6302.623438,5970.388760,7696.777725,10680.792820
Croatia,3119.236520,4338.231617,5477.890018,6960.297861,9164.090127,11305.385170,13221.821840,13822.583940,8447.794873,9875.604515,11628.388950,14619.222720
Czech Republic,6876.140250,8256.343918,10136.867130,11399.444890,13108.453600,14800.160620,15377.228550,16310.443400,14297.021220,16048.514240,17596.210220,22833.308510
Denmark,9692.385245,11099.659350,13583.313510,15937.211230,18866.207210,20422.901500,21688.040480,25116.175810,26406.739850,29804.345670,32166.500060,35278.418740
Finland,6424.519071,7545.415386,9371.842561,10921.636260,14358.875900,15605.422830,18533.157610,21141.012230,20647.164990,23723.950200,28204.590570,33207.084400
France,7029.809327,8662.834898,10560.485530,12999.917660,16107.191710,18292.635140,20293.897460,22066.442140,24703.796150,25889.784870,28926.032340,30470.016700
Germany,7144.114393,10187.826650,12902.462910,14745.625610,18016.180270,20512.921230,22031.532740,24639.185660,26505.303170,27788.884160,30035.801980,32170.374420
Greece,3530.690067,4916.299889,6017.190733,8513.097016,12724.829570,14195.524280,15268.420890,16120.528390,17541.496340,18747.698140,22514.254800,27538.411880
Hungary,5263.673816,6040.180011,7550.359877,9326.644670,10168.656110,11674.837370,12545.990660,12986.479980,10535.628550,11712.776800,14843.935560,18008.944440
Iceland,7267.688428,9244.001412,10350.159060,13319.895680,15798.063620,19654.962470,23269.607500,26923.206280,25144.392010,28061.099660,31163.201960,36180.789190
Ireland,5210.280328,5599.077872,6631.597314,7655.568963,9530.772896,11150.981130,12618.321410,13872.866520,17558.815550,24521.947130,34077.049390,40675.996350
Italy,4931.404155,6248.656232,8243.582340,10022.401310,12269.273780,14255.984750,16537.483500,19207.234820,22013.644860,24675.024460,27968.098170,28569.719700
Montenegro,2647.585601,3682.259903,4649.593785,5907.850937,7778.414017,9595.929905,11222.587620,11732.510170,7003.339037,6465.613349,6557.194282,9253.896111
Netherlands,8941.571858,11276.193440,12790.849560,15363.251360,18794.745670,21209.059200,21399.460460,23651.323610,26790.949610,30246.130630,33724.757780,36797.933320
Norway,10095.421720,11653.973040,13450.401510,16361.876470,18965.055510,23311.349390,26298.635310,31540.974800,33965.661150,41283.164330,44683.975250,49357.190170
Poland,4029.329699,4734.253019,5338.752143,6557.152776,8006.506993,9508.141454,8451.531004,9082.351172,7738.881247,10159.583680,12002.239080,15389.924680
Portugal,3068.319867,3774.571743,4727.954889,6361.517993,9022.247417,10172.485720,11753.842910,13039.308760,16207.266630,17641.031560,19970.907870,20509.647770
Romania,3144.613186,3943.370225,4734.997586,6470.866545,8011.414402,9356.397240,9605.314053,9696.273295,6598.409903,7346.547557,7885.360081,10808.475610
Serbia,3581.459448,4981.090891,6289.629157,7991.707066,10522.067490,12980.669560,15181.092700,15870.878510,9325.068238,7914.320304,7236.075251,9786.534714
Slovak Republic,5074.659104,6093.262980,7481.107598,8412.902397,9674.167626,10922.664040,11348.545850,12037.267580,9498.467723,12126.230650,13638.778370,18678.314350
Slovenia,4215.041741,5862.276629,7402.303395,9405.489397,12383.486200,15277.030170,17866.721750,18678.534920,14214.716810,17161.107350,20660.019360,25768.257590
Spain,3834.034742,4564.802410,5693.843879,7993.512294,10638.751310,13236.921170,13926.169970,15764.983130,18603.064520,20445.298960,24835.471660,28821.063700
Sweden,8527.844662,9911.878226,12329.441920,15258.296970,17832.024640,18855.725210,20667.381250,23586.929270,23880.016830,25266.594990,29341.630930,33859.748350
Switzerland,14734.232750,17909.489730,20431.092700,22966.144320,27195.113040,26982.290520,28397.715120,30281.704590,31871.530300,32135.323010,34480.957710,37506.419070
Turkey,1969.100980,2218.754257,2322.869908,2826.356387,3450.696380,4269.122326,4241.356344,5089.043686,5678.348271,6601.429915,6508.085718,8458.276384
United Kingdom,9979.508487,11283.177950,12477.177070,14142.850890,15895.116410,17428.748460,18232.424520,21664.787670,22705.092540,26074.531360,29478.999190,33203.261280

In [61]:
greece = europe.loc["Greece"]

In [62]:
greece

gdpPercap_1952     3530.690067
gdpPercap_1957     4916.299889
gdpPercap_1962     6017.190733
gdpPercap_1967     8513.097016
gdpPercap_1972    12724.829570
gdpPercap_1977    14195.524280
gdpPercap_1982    15268.420890
gdpPercap_1987    16120.528390
gdpPercap_1992    17541.496340
gdpPercap_1997    18747.698140
gdpPercap_2002    22514.254800
gdpPercap_2007    27538.411880
Name: Greece, dtype: float64

In [63]:
greece.index()

TypeError: 'Index' object is not callable

In [64]:
greece.index

Index(['gdpPercap_1952', 'gdpPercap_1957', 'gdpPercap_1962', 'gdpPercap_1967',
       'gdpPercap_1972', 'gdpPercap_1977', 'gdpPercap_1982', 'gdpPercap_1987',
       'gdpPercap_1992', 'gdpPercap_1997', 'gdpPercap_2002', 'gdpPercap_2007'],
      dtype='object')

In [65]:
gdpgreece = greece.loc["gdpPercap_2007"]

In [66]:
gdpgreece

27538.41188

In [67]:
iceland = europe.loc["Iceland"]

In [68]:
iceland

gdpPercap_1952     7267.688428
gdpPercap_1957     9244.001412
gdpPercap_1962    10350.159060
gdpPercap_1967    13319.895680
gdpPercap_1972    15798.063620
gdpPercap_1977    19654.962470
gdpPercap_1982    23269.607500
gdpPercap_1987    26923.206280
gdpPercap_1992    25144.392010
gdpPercap_1997    28061.099660
gdpPercap_2002    31163.201960
gdpPercap_2007    36180.789190
Name: Iceland, dtype: float64

In [69]:
gdpiceland = iceland.loc["gdpPercap_1952"]

In [70]:
gdpiceland

7267.688428

In [74]:
europe.loc['Greece','gdpPercap_2007']

27538.41188

In [76]:
europe.loc[['Iceland','Greece'],['gdpPercap_1952','gdpPercap_2007']] # first subset the rows, then the years

         gdpPercap_1952  gdpPercap_2007
country
Iceland     7267.688428     36180.78919
Greece      3530.690067     27538.41188